version: '2.1'

services:
  db-service:
    image: mysql:5.7
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=myPassword121#
      - MYSQL_DATABASE=droneApplication
      - MYSQL_USER=root
      - MYSQL_PASSWORD=asher
    container_name: mysql-db